### ISSUE TITLE
Indexes in wrong order issue.

### ISSUE THREAD

**Issue by harryghgim** [pawel-slowik/zsh-guide-epub#1]
Hi. First of all thanks for zsh guide epub git repository. I cloned your repository and installed requirements, and then run .py file. An epub file was made, but it seems its indexes are in random order. 

<img width="1258" alt="Screen Shot 2020-05-04 at 11 56 48 AM" src="https://user-images.githubusercontent.com/35060447/80933401-89b87c00-8dfe-11ea-8a2d-8e8188cdfe4c.png">

It'd be really appreciated if you let me know how it could be fixed. Thanks!

**Comment by pawel-slowik** [comment]
Hi, I'm afraid I can't help you with that. My script only works for the book titled _A User's Guide to the Z-Shell_ by Peter Stephenson, but your screenshot shows _The Z Shell Manual_ by Paul Falstad. This is a different book, which means the EPUB file was not created by my script. Therefore I don't know why the table of contents is randomized like this.

**Comment by harryghgim** [comment]
Oh, my bad😅. Sorry for the confusion, I showed you the wrong one. I still has some issue though with A User's Guide to the Z-Shell by Peter Stephenson. When I scroll down Table of Contents, I can only see the first few indexes of chapters, and if I scroll all the way down my ebook screen shows no text at all. Can I get any help on this? I'm sure I'm referring the right book this time! Thanks!

<img width="1190" alt="Screen Shot 2020-05-05 at 9 49 55 AM" src="https://user-images.githubusercontent.com/35060447/81026848-82ed4000-8eb6-11ea-9b31-b208555accb3.png">

<img width="1190" alt="Screen Shot 2020-05-05 at 9 58 41 AM" src="https://user-images.githubusercontent.com/35060447/81027105-5685f380-8eb7-11ea-9e73-ff80531b9fa8.png">

**Comment by pawel-slowik** [comment]
I'm not sure if I can help you with this because I can't reproduce the issue. I have tested the EPUB file with FBReader on Linux, ReadEra on an Android phone and on a 2011 Nook Simple Touch. None of these display the issues you described.

Some EPUB validation tools show warnings for the original Table of Contents, because that file is not fully XHTML compliant. Therefore I have removed the original ToC and replaced it with a [NCX ToC](https://wiki.mobileread.com/wiki/NCX#TOC). This means that there's no separate chapter with the ToC now, instead it should be available as a icon or button in your reader. I hope this fixes the problem.

**Comment by gwanghyeongim** [comment]
I use Mac and Books(an app in Mac), so maybe it's compatibility issue. I'll either read as is, or try finding another way. Thanks anyway!

**Comment by harryghgim** [comment]
> I'm not sure if I can help you with this because I can't reproduce the issue. I have tested the EPUB file with FBReader on Linux, ReadEra on an Android phone and on a 2011 Nook Simple Touch. None of these display the issues you described.
> 
> Some EPUB validation tools show warnings for the original Table of Contents, because that file is not fully XHTML compliant. Therefore I have removed the original ToC and replaced it with a [NCX ToC](https://wiki.mobileread.com/wiki/NCX#TOC). This means that there's no separate chapter with the ToC now, instead it should be available as a icon or button in your reader. I hope this fixes the problem.

I cloned your repository and generated epub file, and now I can see all indexes clearly. Thank you so much for your efforts! 👍

<img width="1258" alt="Screen Shot 2020-05-26 at 2 31 23 AM" src="https://user-images.githubusercontent.com/35060447/82833554-416e1480-9ef9-11ea-945a-3625fca995ab.png">
